#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

cd $OUTPUT_FOLDER
# echo $CODE >code.py
cat $INPUT_FOLDER/input.json | jq -r '.code' >code.py

echo "Generating requirements.txt ..." | tee $LOG_FILE
pipreqs --savepath=requirements.txt --force code.py

echo "Creating environment ..." | tee -a $LOG_FILE
python3 -m venv .venv
.venv/bin/pip install -U pip wheel
.venv/bin/pip install -r requirements.txt

echo "Executing code ...." | tee -a $LOG_FILE
.venv/bin/python3 code.py 2>>&1 | tee -a $LOG_FILE


echo "DONE" | tee -a $LOG_FILE



# then retrieve the output and move it to the $OUTPUT_FOLDER
# as defined in the output labels


# For example: cp output.csv $OUTPUT_FOLDER or to $OUTPUT_FOLDER/output.json using jq
# cat > $OUTPUT_FOLDER/output.json << EOF
# {

#     "output_1":"some_stuff"

# }
# EOF

