#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

cd $OUTPUT_FOLDER
# echo $CODE >code.py
mkdir -p src
cat $INPUT_FOLDER/input.json | jq -r '.code' >src/code.py

echo "Generating requirements.txt ..." | tee $LOG_FILE
pipreqs --savepath=requirements.txt --force src | tee -a $LOG_FILE

echo "Creating environment ..." | tee -a $LOG_FILE
python3 -m venv --system-site-packages --symlinks --upgrade .venv
.venv/bin/pip install -U pip wheel setuptools
.venv/bin/pip install -r requirements.txt | tee -a $LOG_FILE

echo "Executing code ...." | tee -a $LOG_FILE
.venv/bin/python3 src/code.py 2>&1 | tee -a $LOG_FILE


echo "DONE" | tee -a $LOG_FILE



# then retrieve the output and move it to the $OUTPUT_FOLDER
# as defined in the output labels


# For example: cp output.csv $OUTPUT_FOLDER or to $OUTPUT_FOLDER/output.json using jq
# cat > $OUTPUT_FOLDER/output.json << EOF
# {

#     "output_1":"some_stuff"

# }
# EOF

