#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

export LOG_FILE=$LOG_FOLDER/log.dat

pushd $OUTPUT_FOLDER
python3 /home/${SC_USER_NAME}/src/main.py setup | tee $LOG_FILE

/bin/bash main.sh  | tee -a $LOG_FILE

python3 /home/${SC_USER_NAME}/src/main.py teardown | tee -a $LOG_FILE
popd